### ISSUE TITLE
泛型通配符还是这个最经典

### ISSUE THREAD

**Issue by LcxAndroidwawa** [TotemsCN/Base#12]
. List<? extends T>和List <? super T>之间有什么区别 ?
 考察的就是通配符修饰类型的上界和下界问题   <? extends T>是说明必须是T或者T的子类 <? super T>说明必须是T或者T的父类   List<? extends T>可以接受任何继承自T的类型的List，而List<? super T>可以接受任何T的父类构成的List。例如List<? extends Number>可以接受List<Integer>或List<Float> 而List<? super Number>的话 就只能接收Number或者Number的父类比如Object 我也是昨晚复习看的 觉得很经典

**Comment by yanbober** [comment]
已收录，详见 Java.md 19-n 题，谢谢！
