### ISSUE TITLE
基本数据类型的==与equals

### ISSUE THREAD

**Issue by ONARAINYDAY** [TotemsCN/Base#15]
Integer a = 444;
int b = 444;
System.out.println(a==b);//true
System.out.println(a.equals(b));//true
== 比较的数值是否相等。
Integer的equals内部也是值的比较。

**Comment by yanbober** [comment]
@ONARAINYDAY 可参见 Java 面试题 16 题整理。
注意包装类型与非包装类型 == 比较的自动拆箱机制；
注意 equals 的参数自动装箱机制和不会类型转换机制；
所以你的问题同理会得到如下一道题：
String a = "12";
int b = 12;
System.out.println(a.equals(b));  //false
原理就是自动装箱但不会类型转换。
