### ISSUE TITLE
逛stackoverflow时 看见一个wait（）和notify（）的简单场景 特此来提issue 每日一题有些时候 太理论 没代码 

### ISSUE THREAD

**Issue by LcxAndroidwawa** [TotemsCN/Base#19]
https://stackoverflow.com/questions/2536692/a-simple-scenario-using-wait-and-notify-in-java

**Comment by yanbober** [comment]
已经采纳入库链接！谢谢您的建议，欢迎为其他 Base 补充优质案例或者博文链接，作者时间有限，只能做到题目的引导作用，细节深入依据不同层次受众需要自己酌情补充，所以还是很乐意以 issues 的方式补充链接，希望Base可以变成一个纯干货的速查手册。
